// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuwlduglipdmsvooktcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1d2xkdWdsaXBkbXN2b29rdGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzA1MDksImV4cCI6MjA2MzU0NjUwOX0.4QC2D0fH1trpzB_i3edyjRzd5-F00z3BTBMHZvKvSm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);